# Generated by Django 3.1.5 on 2021-01-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('supermarket', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('start_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cost_type', models.BooleanField(default=True)),
            ],
        ),
    ]
