# Generated by Django 3.1.5 on 2021-01-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_donate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='user',
            field=models.CharField(default='aoc', max_length=100),
        ),
    ]
